apiVersion: "v1"
kind: Pod
metadata:
  name: curltest
  labels:
    name: curltest
    owner: Praparn_L
    version: "1.0"
    module: curltest
    environment: development
spec:
  containers:
    - name: curltest
      image: labdocker/nginx:http2
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "admin"
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""